---
- hosts: all
  become: yes
  tasks:
    - name: Install EPEL repo
      package:
        name: 
          - epel-release
    - name: install the package from a remote repo
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: Install EPEL repo
      yum:
        name: 
          - yum-utils
    - name: Enable remi repo
      shell: |
        sudo yum-config-manager --enable remi-php72 -y
        sudo yum update -y


    - name: Install nginx
      package:
        name: 
          - nginx

    
    - name: backup existing config file
      command: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
  
    - name: upload the nginx config file
      copy:
        src: /Users/chinmaya/Documents/GitHub/webApp-loadbalancer-DB-TOSCA/playbooks/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
    


    - name: Start nginx
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Set attributes
      set_stats:
        data:
          site_config_dir: /etc/nginx/conf.d
